server:
  port: 7006
  servlet:
    context-path: /login
    
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logindata
    username: root
    password: 'Vignesh333#'
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    
  jackson:
    serialization:
      fail-on-empty-beans: false
    
  
  
